Revert "separate workflows for nicer status reporting"
This reverts commit ca4a2fa37f3ca76eac744405a5a28943550d0af5.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,23 +1,57 @@
 name: Package & release
 
 on:
-  workflow_call:
-    inputs:
-      semver:
-        required: true
-        type: string
-  workflow_dispatch:
-    inputs:
-      semver:
-        required: true
-        type: string
+  push:
 
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
+
+  version:
+    runs-on: ubuntu-latest
+
+    outputs:
+      semver: ${{ steps.set_version.outputs.semver }}
+      release_me: ${{ steps.release_me.outputs.release_me }}
+
+    steps:
+      - uses: actions/checkout@v5
+
+      - id: tag_check
+        if: ${{ startsWith( '/refs/tags/v', github.ref) }}
+        run: echo "TAG=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
+
+      - id: version_go_check
+        if: ${{ github.ref == 'refs/heads/main' }}
+        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf #v5.3.1
+        with:
+          paths: '["version.go"]'
+
+      - id: version_go
+        run: echo VERSION_GO=v$(grep 'const Version = ' version.go | awk --field-separator='"' '{ print $2 }') >> "$GITHUB_OUTPUT"
+
+      - id: version_conflict
+        if: ${{ steps.tag_check.outcome == 'success' && steps.tag_check.outputs.TAG != steps.version_go.outputs.VERSION_GO }}
+        run: |
+          echo "::error title=Mismatched versions::Tag ${{ steps.tag_check.outputs.TAG }} vs version.go ${{ steps.version_go.outputs.VERSION_GO }}"
+          exit 1
+
+      - id: release_me
+        run: echo "RELEASE_ME=${{ steps.tag_check.outcome == 'success' || steps.version_go_check.outputs.should_skip == 'false' }}" >> "$GITHUB_OUTPUT"
+
+      - id: set_version
+        if: ${{ steps.release_me.outputs.release_me == 'true' }}
+        run: echo "SEMVER=${{ steps.tag_check.outputs.TAG || steps.version_go.outputs.VERSION_GO }}" >> "$GITHUB_OUTPUT"
+
+      - id: create_tag
+        if: ${{ steps.tag_check.outcome == 'skipped' && steps.release_me.outputs.release_me == 'true' }}
+        run: git tag ${{ steps.set_version.outputs.semver }} && git push --tags
+
   docker:
+    needs: version
+    if: ${{ needs.version.outputs.release_me == 'true' }}
     runs-on: ubuntu-latest
 
     permissions:
@@ -50,7 +84,7 @@ jobs:
         uses: docker/metadata-action@032a4b3bda1b716928481836ac5bfe36e1feaad6
         with:
           tags: |
-            type=semver,pattern={{raw}},value=${{ inputs.semver }}
+            type=semver,pattern={{raw}},value=${{ needs.version.outputs.semver }}
           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
 
       - name: Build and push Docker image
@@ -63,6 +97,8 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
 
   github:
+    needs: version
+    if: ${{ needs.version.outputs.release_me == 'true' }}
     runs-on: ubuntu-latest
 
     permissions:
@@ -86,4 +122,4 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
-          gh release create ${{ inputs.semver }} --generate-notes 'snaggle#Snaggle ${{ inputs.semver }}'
+          gh release create ${{ needs.version.outputs.semver }} --generate-notes 'snaggle#Snaggle ${{ needs.version.outputs.semver }}'
